# Generated by Django 4.2.7 on 2023-11-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaSAP',
            fields=[
                ('DocNum', models.IntegerField(primary_key=True, serialize=False)),
                ('DocDate', models.DateTimeField()),
                ('U_CONTAINER', models.CharField(max_length=100)),
                ('U_FECHA_BL', models.DateField()),
                ('CardName', models.CharField(max_length=100)),
                ('CardCode', models.CharField(max_length=100)),
                ('U_ESTADO_CONTENEDOR', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'contenedorestransito',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('DocNum', models.IntegerField(primary_key=True, serialize=False)),
                ('DocDate', models.DateTimeField()),
                ('U_CONTAINER', models.CharField(max_length=100)),
                ('U_FECHA_BL', models.DateTimeField()),
                ('CardCode', models.CharField(max_length=100)),
                ('CardName', models.CharField(max_length=100)),
                ('U_ESTADO_CONTENEDOR', models.CharField(max_length=50)),
            ],
        ),
    ]
