# Generated by Django 4.2.7 on 2023-11-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='DocDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='U_FECHA_BL',
            field=models.DateTimeField(null=True),
        ),
    ]
