# Generated by Django 4.2.7 on 2023-11-19 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenedores', '0002_alter_factura_docdate_alter_factura_u_fecha_bl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('iso_code', models.CharField(max_length=10)),
                ('size_type', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country_code', models.CharField(max_length=10)),
                ('locode', models.CharField(blank=True, max_length=20, null=True)),
                ('bic_code', models.CharField(blank=True, max_length=20, null=True)),
                ('smdg_code', models.CharField(blank=True, max_length=20, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('country_code', models.CharField(max_length=10)),
                ('locode', models.CharField(max_length=20, unique=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('timezone', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prepol_date', models.DateTimeField()),
                ('pol_date', models.DateTimeField()),
                ('pod_date', models.DateTimeField(blank=True, null=True)),
                ('postpod_date', models.DateTimeField(blank=True, null=True)),
                ('pod_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pod', to='contenedores.location')),
                ('pol_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pol', to='contenedores.location')),
                ('postpod_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postpod', to='contenedores.location')),
                ('prepol_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepol', to='contenedores.location')),
            ],
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('imo', models.PositiveIntegerField(unique=True)),
                ('call_sign', models.CharField(max_length=20, unique=True)),
                ('mmsi', models.PositiveIntegerField(unique=True)),
                ('flag', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=20)),
                ('sealine', models.CharField(max_length=20)),
                ('sealine_name', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField()),
                ('total_api_calls', models.PositiveIntegerField()),
                ('used_api_calls', models.PositiveIntegerField()),
                ('remaining_api_calls', models.PositiveIntegerField()),
                ('total_shipments', models.PositiveIntegerField()),
                ('used_shipments', models.PositiveIntegerField()),
                ('remaining_shipments', models.PositiveIntegerField()),
                ('containers', models.ManyToManyField(to='contenedores.container')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenedores.route')),
                ('vessels', models.ManyToManyField(to='contenedores.vessel')),
            ],
        ),
        migrations.CreateModel(
            name='RouteData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.JSONField()),
                ('type', models.CharField(max_length=10)),
                ('transport_type', models.CharField(max_length=20)),
                ('pin_location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contenedores.location')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='route_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contenedores.routedata'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=20)),
                ('event_code', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('actual', models.BooleanField()),
                ('is_additional_event', models.BooleanField()),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('transport_type', models.CharField(blank=True, max_length=20, null=True)),
                ('voyage', models.CharField(blank=True, max_length=20, null=True)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenedores.facility')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenedores.location')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenedores.shipment')),
                ('vessel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenedores.vessel')),
            ],
        ),
    ]
