# Generated by Django 4.2.7 on 2023-11-24 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenedores', '0003_container_facility_location_route_vessel_shipment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.RemoveField(
            model_name='event',
            name='shipment',
        ),
        migrations.RemoveField(
            model_name='event',
            name='vessel',
        ),
        migrations.RemoveField(
            model_name='route',
            name='pod_location',
        ),
        migrations.RemoveField(
            model_name='route',
            name='pol_location',
        ),
        migrations.RemoveField(
            model_name='route',
            name='postpod_location',
        ),
        migrations.RemoveField(
            model_name='route',
            name='prepol_location',
        ),
        migrations.RemoveField(
            model_name='route',
            name='route_data',
        ),
        migrations.RemoveField(
            model_name='routedata',
            name='pin_location',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='containers',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='route',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='vessels',
        ),
        migrations.DeleteModel(
            name='Container',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Facility',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
        migrations.DeleteModel(
            name='RouteData',
        ),
        migrations.DeleteModel(
            name='Shipment',
        ),
        migrations.DeleteModel(
            name='Vessel',
        ),
    ]
