# Generated by Django 4.2.7 on 2023-11-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedores', '0004_remove_event_facility_remove_event_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contenedor',
            fields=[
                ('codigo', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('ultimo_evento_desc', models.CharField(max_length=150)),
                ('ultimo_evento_fecha', models.DateTimeField()),
                ('id_viaje', models.CharField(max_length=30)),
                ('puerto_descarga_eta', models.DateTimeField()),
                ('puerto_descarga_nom', models.CharField(max_length=50)),
                ('puerto_descarga_cod_pais', models.CharField(max_length=10)),
                ('puerto_descarga_cod', models.CharField(max_length=10)),
                ('buque_nom', models.CharField(max_length=50)),
                ('buque_imo', models.CharField(max_length=30)),
                ('buque_mmsi', models.CharField(max_length=30)),
                ('buque_flag', models.CharField(max_length=10)),
                ('buque_lat', models.FloatField()),
                ('buque_lng', models.FloatField()),
                ('buque_ult_actualizacion', models.DateTimeField()),
                ('puerto_salida_atd', models.DateTimeField()),
                ('puerto_salida_cod_pais', models.CharField(max_length=10)),
                ('puerto_Salida_cod', models.CharField(max_length=10)),
                ('puerto_llegada_cod_pais', models.CharField(max_length=10)),
                ('puerto_llegada_cod', models.CharField(max_length=10)),
                ('puerto_llegada_eta', models.DateTimeField()),
            ],
        ),
    ]
