# Generated by Django 4.2.7 on 2023-11-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedores', '0005_contenedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenedor',
            name='buque_flag',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='buque_imo',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='buque_lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='buque_lng',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='buque_mmsi',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='buque_nom',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='buque_ult_actualizacion',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='id_viaje',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='puerto_Salida_cod',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='puerto_descarga_cod',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='puerto_descarga_cod_pais',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='puerto_descarga_eta',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='puerto_descarga_nom',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='puerto_llegada_cod',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='puerto_llegada_cod_pais',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='puerto_llegada_eta',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='puerto_salida_atd',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='puerto_salida_cod_pais',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='ultimo_evento_desc',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='ultimo_evento_fecha',
            field=models.DateTimeField(null=True),
        ),
    ]
