# Generated by Django 4.2.7 on 2023-11-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedores', '0006_alter_contenedor_buque_flag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenedor',
            name='ultima_actualizacion',
            field=models.DateTimeField(null=True),
        ),
    ]
