# Generated by Django 4.2.7 on 2023-11-24 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenedores', '0007_contenedor_ultima_actualizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='Contenedor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenedores.contenedor'),
        ),
    ]
