# Generated by Django 4.2.7 on 2023-11-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedores', '0008_factura_contenedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenedor',
            name='estado',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
