# Generated by Django 4.2.7 on 2023-11-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedores', '0010_rename_puerto_salida_cod_contenedor_puerto_salida_cod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contenedor',
            old_name='ultima_actualizacion',
            new_name='ultima_actualizacion_tracking',
        ),
        migrations.AddField(
            model_name='contenedor',
            name='ultima_actualizacion_modelo',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
