# Generated by Django 4.2.7 on 2023-11-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedores', '0011_rename_ultima_actualizacion_contenedor_ultima_actualizacion_tracking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenedor',
            name='naviera_nom',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
