# Generated by Django 4.2.8 on 2023-12-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedores', '0013_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(default='imagen_perfil_default.jpg', upload_to='usuarios/'),
        ),
    ]
