# Generated by Django 4.2.4 on 2023-12-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedores', '0014_alter_usuario_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenedor',
            name='pol',
            field=models.DateTimeField(null=True),
        ),
    ]
